### PR TITLE
Fix register reference (`t0` -> `t1`)

### PR DESCRIPTION
**Pull request by michalbiesek**
This will corresponds to:
```
3. Loading `2` into temporary register `t1`. (address: `900f8`)
4. Storing the contents of `t1` on the stack. (address: `900fc`)
```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Thanks for the fix @michalbiesek! I think we should update the referenced description rather than the assembly output -- would you be open to updating to do that here?

**Comment by michalbiesek** [comment]
Thanks for the response, @hasheddan, and your great work with the blog. I've built the main.go from the blog post above with Mango Pi MQ-Pro and Go 1.18, and here is the assembly output from objdump.
```
0000000000090830 <main.add>:
   90830:       00813283                ld      t0,8(sp)
   90834:       01013303                ld      t1,16(sp)
   90838:       006282b3                add     t0,t0,t1
   9083c:       00513c23                sd      t0,24(sp)
   90840:       00008067                ret
   90844:       0000                    unimp
        ...
0000000000090848 <main.main>:
   90848:	010db503          	ld	a0,16(s11)
   9084c:	00256663          	bltu	a0,sp,90858 <main.main+0x10>
   90850:	9c0da2ef          	jal	t0,6aa10 <runtime.morestack_noctxt>
   90854:	ff5ff06f          	j	90848 <main.main>
   90858:	fa113423          	sd	ra,-88(sp)
   9085c:	fa810113          	add	sp,sp,-88
   90860:	00100293          	li	t0,1
   90864:	00513423          	sd	t0,8(sp)
   90868:	00200313          	li	t1,2
   9086c:	00613823          	sd	t1,16(sp)
   90870:	fc1ff0ef          	jal	90830 <main.add>
   90874:	01813283          	ld	t0,24(sp)
   90878:	04013423          	sd	zero,72(sp)
   9087c:	04013823          	sd	zero,80(sp)
   90880:	00513423          	sd	t0,8(sp)
   90884:	9c4880ef          	jal	18a48 <runtime.convT64>
   90888:	01013283          	ld	t0,16(sp)
   9088c:	00016317          	auipc	t1,0x16
   90890:	e3430313          	add	t1,t1,-460 # a66c0 <type.*+0x66c0>
   90894:	04613423          	sd	t1,72(sp)
   90898:	04513823          	sd	t0,80(sp)
   9089c:	000b8297          	auipc	t0,0xb8
   908a0:	8f42b283          	ld	t0,-1804(t0) # 148190 <os.Stdout>
   908a4:	00044317          	auipc	t1,0x44
   908a8:	c7430313          	add	t1,t1,-908 # d4518 <go.itab.*os.File,io.Writer>
   908ac:	00613423          	sd	t1,8(sp)
   908b0:	00513823          	sd	t0,16(sp)
   908b4:	04810293          	add	t0,sp,72
   908b8:	00513c23          	sd	t0,24(sp)
   908bc:	00100293          	li	t0,1
   908c0:	02513023          	sd	t0,32(sp)
   908c4:	02513423          	sd	t0,40(sp)
   908c8:	c00fa0ef          	jal	8acc8 <fmt.Fprintln>
   908cc:	00013083          	ld	ra,0(sp)
   908d0:	05810113          	add	sp,sp,88
   908d4:	00008067          	ret
```
As you can see, the output is pretty similar to the one you currently have in the post. See that in fact we use `t0` and `t1` register not only `t0` in <main.main>:
```
   90860:	00100293          	li	t0,1
   90864:	00513423          	sd	t0,8(sp)
   90868:	00200313          	li	t1,2
   9086c:	00613823          	sd	t1,16(sp)
```
On the other side the part mentioned above in the blog post is presented as:
```
   900f0:       00100293                li      t0,1
   900f4:       00513423                sd      t0,8(sp)
   900f8:       00200293                li      t0,2
   900fc:       00513823                sd      t0,16(sp)
```
Therefore I think the assembly output should be updated. 
If the assembly output will be updated I am not sure what part in description below
```
Loading 1 into temporary register t0. (address: 900f0)
Storing the contents of t0 on the stack. (address: 900f4)
Loading 2 into temporary register t1. (address: 900f8)
Storing the contents of t1 on the stack. (address: 900fc)
Jumping to main.add. (address: 90100)
```
should be modified. I think the description will be accurate.

**Comment by michalbiesek** [comment]
@hasheddan, kindly ping. Out of curiosity I'm wondering if there's anything else I need to clarify regarding the intention of my patch.

**Review by hasheddan — APPROVED** [review]
@michalbiesek apologies for the delay and thanks for following up! I also double checked and verified that you are correct! Thanks again :)

**Pull request merged**
